"""Dynamic Range Database lookups (dr.loudness-war.info) for the renderer card.

The panel knows what is playing but not how hard it was mastered: two
pressings of the same album can differ by ten DR, and the loudest one is
usually the one a streaming service serves.  This module asks the community
database which versions exist and what each one measures, so the answer to
"is there a better master of this?" is one button away from the now-playing
line.

There is no public API — the site is server-rendered HTML — so the pages are
parsed.  Only two of them are: the album list (`/`, `/album/list/...`) and one
album's detail page (`/album/view/<id>`).  Both are machine-generated by the
same template, and the parser reads them structurally (table headers name
their columns, `<th scope=row>` labels name their fields) rather than by
position, so a column added upstream shifts nothing.

Everything here is read-only, cached for `cache_ttl`, and paced by a shared
minimum interval: a listener pressing the button repeatedly must not turn the
panel into a scraper.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from html.parser import HTMLParser
import gzip
import re
import threading
import time
import urllib.error
import urllib.parse
import urllib.request

DEFAULT_BASE_URL = "https://dr.loudness-war.info"

# Rows per page in the site's own listing.  Only used to tell a short last
# page from a full one when deciding whether more results exist.
PAGE_SIZE = 25


@dataclass
class Settings:
    enabled: bool = True
    base_url: str = DEFAULT_BASE_URL
    # The box is on the far side of a domestic link and the panel is polled by
    # a browser: a lookup that cannot answer promptly should fail, not hang a
    # request thread.
    timeout: float = 12.0
    cache_ttl: float = 900.0
    # 3 pages = 75 albums, requested already sorted by DR descending, so a
    # truncated result still holds the best masters the database knows.
    max_pages: int = 3
    # Details are fetched one album at a time, on demand; this caps what the
    # "locate the playing track" sweep may ask for in one go.
    max_detail_lookups: int = 24
    min_request_interval: float = 0.3
    max_response_bytes: int = 4 * 1024 * 1024
    user_agent: str = "open-media-drc panel (dynamic range lookup)"


class DrDbError(RuntimeError):
    """A lookup that could not be answered — network, HTTP or parse."""


# ── HTML ────────────────────────────────────────────────────────────────────

_WS = re.compile(r"\s+")
_ALBUM_ID = re.compile(r"/album/view/(\d+)")
# "DR7   0.00 dB   -8.34 dB   4:12 01-I Ain't" — the per-track line every
# DR-meter build writes into the log people upload with an album.  Tools
# differ below this line (MAAT prints more columns, dr14_tmeter fewer), so
# anything that does not match is simply not a track line.
_LOG_TRACK = re.compile(
    r"^\s*DR(\d+)\s+(-?[\d.]+\s*dB)\s+(-?[\d.]+\s*dB)\s+(\d+:\d{2})\s+(.*?)\s*$")


def _clean(text: str) -> str:
    return _WS.sub(" ", text).strip()


class _TableParser(HTMLParser):
    """Every `<table>` on the page as rows of cells.

    A cell keeps its collapsed text, its raw text (log files are `<pre>` and
    their line breaks carry meaning), the hrefs it links to and the DR badges
    it contains — which is everything either page expresses.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.tables: list[list[list[dict]]] = []
        self._table: list[list[dict]] | None = None
        self._row: list[dict] | None = None
        self._cell: dict | None = None
        self._badge: dict | None = None

    # HTMLParser hooks
    def handle_starttag(self, tag: str, attrs) -> None:
        attr = dict(attrs)
        if tag == "table":
            self._table = []
        elif tag == "tr" and self._table is not None:
            self._row = []
        elif tag in ("td", "th") and self._row is not None:
            self._cell = {"header": tag == "th", "parts": [],
                          "links": [], "badges": []}
        elif self._cell is not None:
            if tag == "a" and attr.get("href"):
                self._cell["links"].append(attr["href"])
            elif tag == "span" and "badge-dr" in (attr.get("class") or ""):
                self._badge = {"class": attr.get("class", ""), "text": ""}
                self._cell["badges"].append(self._badge)
            elif tag == "br":
                self._cell["parts"].append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag == "span" and self._badge is not None:
            self._badge = None
        elif tag in ("td", "th") and self._cell is not None:
            raw = "".join(self._cell["parts"])
            self._cell["raw"] = raw
            self._cell["text"] = _clean(raw)
            if self._row is not None:
                self._row.append(self._cell)
            self._cell = None
        elif tag == "tr" and self._row is not None:
            if self._row:
                self._table.append(self._row)      # type: ignore[union-attr]
            self._row = None
        elif tag == "table" and self._table is not None:
            self.tables.append(self._table)
            self._table = None

    def handle_data(self, data: str) -> None:
        if self._badge is not None:
            self._badge["text"] += data
        elif self._cell is not None:
            self._cell["parts"].append(data)

    @classmethod
    def parse(cls, html: str) -> list[list[list[dict]]]:
        parser = cls()
        parser.feed(html)
        parser.close()
        return parser.tables


def _badge_dr(cell: dict) -> int | None:
    """The DR a cell states.  The badge text is the number the site shows;
    its `badge-dr-NN` class is only a colour bucket (everything at or below 7
    is `badge-dr-07`), so the class is a fallback, never the answer."""
    for badge in cell.get("badges", []):
        text = badge["text"].strip()
        if text.isdigit():
            return int(text)
    text = cell.get("text", "").strip()
    return int(text) if text.isdigit() else None


def _album_id(cell: dict) -> int | None:
    for href in cell.get("links", []):
        match = _ALBUM_ID.search(href)
        if match:
            return int(match.group(1))
    return None


def _column_map(header: list[dict]) -> dict:
    """Column name → index, read from the header row.  The DR columns are
    distinguished by their `min`/`max` captions, which is how the site itself
    labels them."""
    index: dict[str, int] = {}
    for position, cell in enumerate(header):
        name = cell.get("text", "").lower()
        if "artist" in name:
            index.setdefault("artist", position)
        elif "album" in name:
            index.setdefault("album", position)
        elif "year" in name:
            index.setdefault("year", position)
        elif "min" in name and "dr" in name:
            index.setdefault("dr_min", position)
        elif "max" in name and "dr" in name:
            index.setdefault("dr_max", position)
        elif "dr" in name:
            index.setdefault("dr", position)
        elif "codec" in name:
            index.setdefault("codec", position)
        elif "source" in name:
            index.setdefault("source", position)
    return index


# Order of the columns as the site has always served them.  Used only when a
# listing arrives with no header row to read.
_POSITIONAL = {"artist": 0, "album": 1, "year": 2, "dr": 3,
               "dr_min": 4, "dr_max": 5, "codec": 6, "source": 7}


def parse_search(html: str, base_url: str = DEFAULT_BASE_URL) -> list[dict]:
    """The album rows of a listing page, in the order the site served them."""
    rows: list[dict] = []
    for table in _TableParser.parse(html):
        header_index: dict = {}
        for cells in table:
            if all(cell["header"] for cell in cells):
                header_index = _column_map(cells)
                continue
            album_id = next((_album_id(cell) for cell in cells
                             if _album_id(cell) is not None), None)
            if album_id is None:
                continue
            index = header_index or _POSITIONAL

            def value(key: str) -> dict | None:
                position = index.get(key)
                return cells[position] if position is not None and position < len(cells) else None

            def text(key: str) -> str:
                cell = value(key)
                return cell["text"] if cell else ""

            def number(key: str) -> int | None:
                cell = value(key)
                return _badge_dr(cell) if cell else None

            rows.append({
                "id":      album_id,
                "artist":  text("artist"),
                "album":   text("album"),
                "year":    text("year"),
                "dr":      number("dr"),
                "dr_min":  number("dr_min"),
                "dr_max":  number("dr_max"),
                "codec":   text("codec"),
                "source":  text("source"),
                "url":     f"{base_url.rstrip('/')}/album/view/{album_id}",
            })
    return rows


# `<th scope="row">` label → field name on the parsed album.  Labels are
# normalised (lower case, no punctuation) before the lookup.
_ALBUM_FIELDS = {
    "artist": "artist",
    "album": "album",
    "year": "year",
    "album dr": "dr",
    "min track dr": "dr_min",
    "max track dr": "dr_max",
    "track dr": "track_dr",
    "codec": "codec",
    "source": "source",
    "label": "label",
    "catalog number": "catalog_number",
    "bar code": "barcode",
    "country": "country",
    "link": "link",
    "comment": "comment",
    "log file": "log",
}


def parse_log_tracks(log: str) -> list[dict]:
    """The per-track table inside an uploaded DR-meter log.

    Album pages carry no structured track list — only the badge row and the
    log someone pasted — but that log names every track next to its DR, which
    is what makes it possible to tell whether a version in the list is the one
    holding the track now playing."""
    tracks: list[dict] = []
    for line in log.splitlines():
        match = _LOG_TRACK.match(line)
        if not match:
            continue
        dr, peak, rms, duration, title = match.groups()
        tracks.append({"dr": int(dr), "peak": _clean(peak), "rms": _clean(rms),
                       "duration": duration, "title": _clean(title)})
    return tracks


def parse_album(html: str, album_id: int | None = None,
                base_url: str = DEFAULT_BASE_URL) -> dict:
    """One album's detail page: the fields it lists, its per-track DR badges,
    and the log it was uploaded with."""
    album: dict = {"id": album_id, "track_dr": [], "tracks": [], "log": ""}
    if album_id is not None:
        album["url"] = f"{base_url.rstrip('/')}/album/view/{album_id}"
    for table in _TableParser.parse(html):
        for cells in table:
            if len(cells) != 2 or not cells[0]["header"]:
                continue
            label = re.sub(r"[.:]", "", cells[0]["text"]).lower().strip()
            field_name = _ALBUM_FIELDS.get(label)
            if field_name is None:
                continue
            cell = cells[1]
            if field_name == "track_dr":
                album["track_dr"] = [int(badge["text"].strip())
                                     for badge in cell["badges"]
                                     if badge["text"].strip().isdigit()]
            elif field_name in ("dr", "dr_min", "dr_max"):
                album[field_name] = _badge_dr(cell)
            elif field_name == "log":
                album["log"] = cell["raw"].strip("\n")
            elif field_name == "link":
                album["link"] = cell["text"]
                album["link_url"] = cell["links"][0] if cell["links"] else ""
            else:
                album[field_name] = cell["text"]
    album["tracks"] = parse_log_tracks(album["log"])
    return album


# ── client ──────────────────────────────────────────────────────────────────

class DrDb:
    """Cached, paced reader for the database's two public pages."""

    def __init__(self, settings: Settings | None = None,
                 fetch=None) -> None:
        self.settings = settings or Settings()
        self._fetch_override = fetch          # tests inject a page source here
        self._cache: dict[str, tuple[float, str]] = {}
        self._lock = threading.Lock()
        self._last_request = 0.0

    # -- transport --

    def _url(self, path: str) -> str:
        return self.settings.base_url.rstrip("/") + path

    def _fetch(self, path: str) -> str:
        """One page, from cache when it is fresh enough.

        The cache is keyed by path, so a detail page opened from the list and
        the same page reopened a minute later cost one request, and the pacing
        below applies only to requests that actually leave the box."""
        now = time.monotonic()
        with self._lock:
            hit = self._cache.get(path)
            if hit and now - hit[0] < self.settings.cache_ttl:
                return hit[1]

        if self._fetch_override is not None:
            html = self._fetch_override(path)
        else:
            html = self._get(path)

        with self._lock:
            self._cache[path] = (time.monotonic(), html)
        return html

    def _pace(self) -> None:
        with self._lock:
            wait = self.settings.min_request_interval - (
                time.monotonic() - self._last_request)
            self._last_request = time.monotonic() + max(0.0, wait)
        if wait > 0:
            time.sleep(wait)

    def _get(self, path: str) -> str:
        self._pace()
        request = urllib.request.Request(self._url(path), headers={
            "User-Agent": self.settings.user_agent,
            "Accept": "text/html",
            "Accept-Encoding": "gzip",
        })
        try:
            with urllib.request.urlopen(request, timeout=self.settings.timeout) as response:
                raw = response.read(self.settings.max_response_bytes)
                if (response.headers.get("Content-Encoding") or "").lower() == "gzip":
                    raw = gzip.decompress(raw)
        except urllib.error.HTTPError as error:
            raise DrDbError(f"{self.settings.base_url} answered HTTP {error.code}") from error
        except urllib.error.URLError as error:
            raise DrDbError(f"cannot reach {self.settings.base_url}: {error.reason}") from error
        except OSError as error:
            raise DrDbError(f"cannot reach {self.settings.base_url}: {error}") from error
        return raw.decode("utf-8", "replace")

    # -- queries --

    def search(self, artist: str = "", album: str = "",
               pages: int | None = None) -> dict:
        """Every version of `album` the database lists, best master first.

        The listing is requested already sorted by album DR descending, so a
        result cut short by `max_pages` still holds the versions worth
        knowing about.  An empty `album` is deliberately allowed: the Qobuz
        renderer puts no album tag in MusicPD's queue, and the artist's whole
        shelf is then the only honest starting point."""
        artist, album = artist.strip(), album.strip()
        if not artist and not album:
            raise DrDbError("nothing to look up — give an artist or an album")
        query = urllib.parse.urlencode(
            {key: value for key, value in (("artist", artist), ("album", album)) if value})
        limit = max(1, pages or self.settings.max_pages)

        rows: list[dict] = []
        seen: set[int] = set()
        truncated = False
        for page in range(1, limit + 1):
            html = self._fetch(f"/album/list/{page}/dr/desc?{query}")
            found = parse_search(html, self.settings.base_url)
            fresh = [row for row in found if row["id"] not in seen]
            seen.update(row["id"] for row in fresh)
            rows.extend(fresh)
            if len(found) < PAGE_SIZE:
                break
            if page == limit:
                truncated = True

        rows.sort(key=lambda row: (row["dr"] is None, -(row["dr"] or 0),
                                   row["album"].lower()))
        return {"artist": artist, "album": album, "rows": rows,
                "truncated": truncated,
                "search_url": f"{self._url('/')}?{query}"}

    def album(self, album_id: int) -> dict:
        return parse_album(self._fetch(f"/album/view/{int(album_id)}"),
                           int(album_id), self.settings.base_url)


# ── which of these versions is playing ──────────────────────────────────────
#
# The database lists every pressing of a record; the renderer says what is on
# the wire. Neither says which is which, and the tags cannot settle it: no
# renderer here publishes a year or a label (upmpdcli sends Artist, Album,
# Title and Track; qobuzconnect2mpd the first three), so an edition cannot be
# named directly. What the queue does carry is the shape of the record — how
# many tracks, in what order, and how long the one playing runs — and editions
# differ there. The Alice In Chains Unplugged DVD rip runs Sludge Factory for
# 7:00 because it keeps the dialogue between songs; the CD's is 4:37. A stream
# measured at 4:37 is the CD.

# Anything bracketed is an edition annotation or a live-venue note, not part of
# the name a database entry and a queue entry would share.
_BRACKETED = re.compile(r"[(\[][^()\[\]]*[)\]]")
# "01-", "1. ", "03 - ": the track number DR-meter logs prefix their titles
# with.
_TRACK_PREFIX = re.compile(r"^\s*\d{1,3}\s*[-._)]\s*")
_NOT_WORD = re.compile(r"[^a-z0-9]+")
# Uploaders drop leading articles as often as they keep them -- this record's
# "The Killer Is Me" is filed as "Killer Is Me" -- and the same cut is made on
# both sides, so nothing that agreed before disagrees now.
_LEADING_ARTICLE = re.compile(r"^(?:the|a|an)\s+")
# A label reaches the two sides differently: Qobuz says "Columbia/Legacy",
# the database entry says "Columbia". Compare the names they are built from,
# not the strings -- and drop the words every label ends in.
_LABEL_NOISE = re.compile(
    r"\b(?:records?|recordings?|music|entertainment|group|ltd|limited|inc|"
    r"llc|gmbh|sa|srl|bv|co|company|label|the)\b", re.I)
_YEAR = re.compile(r"(\d{4})")
# "(Disc 2)", "[CD 1]", ", Disc 2": a database entry for one disc of a set.
_DISC_IN_NAME = re.compile(r"\b(?:disc|disk|cd)\s*(\d{1,2})\b", re.I)
# The transfer's own format, where an entry states it in its name:
# "48kHz-16bit", "[2.0 LPCM 16/48 DVD]", "24/96". Rates are matched only with
# an explicit kHz, so the "448 Kbps" of a Dolby Digital entry is not read as a
# sample rate.
_RATES = "44\\.1|48|88\\.2|96|176\\.4|192|352\\.8|384"
_STATED_BITS_RATE = re.compile(rf"\b(16|24|32)\s*/\s*({_RATES})\b")
_STATED_RATE_BITS = re.compile(rf"\b({_RATES})\s*/\s*(16|24|32)\b")
_STATED_RATE = re.compile(rf"\b({_RATES})\s*k(?:Hz)?\b", re.I)
_STATED_DEPTH = re.compile(r"\b(16|24|32)\s*-?\s*bits?\b", re.I)
# Edition markers in an album name that a 2-channel CD-rate stream cannot be.
_SURROUND_EDITION = re.compile(r"\b(?:5\.1|dvd|blu-?ray|sacd|dts|dolby)\b", re.I)
_VINYL_EDITION = re.compile(r"\b(?:vinyl|lp|pbthal)\b", re.I)


def title_key(title: str) -> str:
    """A track title reduced to what two catalogues would agree on."""
    text = _TRACK_PREFIX.sub("", str(title or "").lower())
    text = _BRACKETED.sub(" ", text)
    text = _NOT_WORD.sub(" ", text).strip()
    return _LEADING_ARTICLE.sub("", text)


def stated_format(name: str) -> tuple:
    """(rate_hz, bits) a database entry declares in its own title, or (None,
    None). Uploaders write the transfer's format there when it is the point of
    the entry -- "MTV Unplugged (DVD 5.1 Mix) 48kHz-16bit" is a different
    transfer from the CD, and says so."""
    text = str(name or "")
    rate = bits = None
    pair = _STATED_BITS_RATE.search(text)
    if pair:
        bits, rate = int(pair.group(1)), float(pair.group(2))
    else:
        pair = _STATED_RATE_BITS.search(text)
        if pair:
            rate, bits = float(pair.group(1)), int(pair.group(2))
    if rate is None:
        loose = _STATED_RATE.search(text)
        if loose:
            rate = float(loose.group(1))
    if bits is None:
        loose = _STATED_DEPTH.search(text)
        if loose:
            bits = int(loose.group(1))
    return (int(rate * 1000) if rate else None, bits)


def format_text(rate, bits) -> str:
    """"96 kHz/24 bit", for a reason a listener can check."""
    if not rate:
        return ""
    text = f"{rate / 1000:g} kHz"
    return f"{text}/{bits} bit" if bits else text


def label_names(label: str) -> set:
    """The distinct imprint names in a label field."""
    names = set()
    for part in re.split(r"[/,;&|]|\s-\s", str(label or "")):
        cleaned = _NOT_WORD.sub(" ", _LABEL_NOISE.sub(" ", part.lower())).strip()
        if len(cleaned) >= 3:
            names.add(cleaned)
    return names


def release_year(value) -> int | None:
    """The year out of "1996", "1996-04-30" or "30/04/1996"."""
    match = _YEAR.search(str(value or ""))
    if not match:
        return None
    year = int(match.group(1))
    return year if 1900 <= year <= 2100 else None


def duration_seconds(text: str) -> int | None:
    """"4:37" or "1:02:11" as seconds."""
    parts = str(text or "").strip().split(":")
    if not parts or not all(p.isdigit() for p in parts) or len(parts) > 3:
        return None
    seconds = 0
    for part in parts:
        seconds = seconds * 60 + int(part)
    return seconds


def identify(playing: dict, album: dict) -> dict:
    """How well one database version matches the track on the wire.

    Only that track is evidence: whatever else sits in the queue was put
    there by a listener, not by a pressing. What a single track carries is
    enough, because it is exactly where two masters of one record differ —
    the same song runs 5:46 on the Unplugged CD and 6:06 on the DVD rip,
    which keeps the dialogue. The tags that name an edition outright, label
    and year, are used when the renderer publishes them.

    Returns a score out of 100, a verdict, and the evidence in both
    directions — the reasons are the point: "Down In A Hole runs 6:06 in this
    version, 5:46 on the wire" is worth more than any number.
    """
    score = 0
    for_, against = [], []
    # Evidence that could not be weighed, and why. A signal that is simply
    # absent from the list reads as a signal that agreed -- so when one side
    # of a comparison has a value and the other does not, say so rather than
    # leaving a silence the reader has to interpret.
    unchecked = []
    evidence = False

    log = album.get("tracks") or []
    log_keys = [title_key(track["title"]) for track in log]

    # -- the track itself, by name and by length ------------------------------
    matched_index = None
    at_its_position = False
    playing_key = title_key(playing.get("title", ""))
    if playing_key and not log_keys:
        unchecked.append("uploaded without a track list, so neither the "
                         "running order nor the track times could be checked")
    if playing_key and log_keys:
        evidence = True
        position = playing.get("track_no")
        if (isinstance(position, int) and 1 <= position <= len(log_keys)
                and log_keys[position - 1] == playing_key):
            matched_index = position - 1
            at_its_position = True
            score += 12
            for_.append(f"track {position} of this version is "
                        f"“{log[matched_index]['title']}”")
        elif playing_key in log_keys:
            matched_index = log_keys.index(playing_key)
            score += 8
            for_.append(f"“{log[matched_index]['title']}” is on this version, "
                        f"at track {matched_index + 1}")
        else:
            score -= 20
            against.append("this version's track list does not name "
                           f"“{playing.get('title')}”")

    wire_seconds = playing.get("duration")
    if matched_index is not None and isinstance(wire_seconds, (int, float)):
        listed = duration_seconds(log[matched_index].get("duration"))
        if listed:
            evidence = True
            delta = abs(listed - round(wire_seconds))
            listed_text = log[matched_index]["duration"]
            wire_text = f"{int(wire_seconds) // 60}:{int(wire_seconds) % 60:02d}"
            title = log[matched_index]["title"]
            if delta <= 3:
                # The right length at the right place in the running order is
                # the strongest thing one track can say -- but not so loud
                # that nothing else can be heard over it. Two rips of one
                # pressing agree to the second, so a few seconds out does mean
                # a different transfer; it should not on its own outweigh an
                # edition whose year and label match.
                score += 45 if at_its_position else 32
                for_.append(f"“{title}” runs {listed_text} here and "
                            f"{wire_text} on the wire")
            elif delta <= 8:
                score += 20
                for_.append(f"“{title}” runs {listed_text} here, close to the "
                            f"{wire_text} on the wire")
            elif delta >= 20:
                score -= 30
                against.append(f"“{title}” runs {listed_text} here but "
                               f"{wire_text} on the wire")

    # -- what the stream's own format rules out ------------------------------
    #
    # A CD is 44.1 kHz/16 bit by definition, so a stream above that is not a
    # rip of one -- an exclusion, not a hint, and the one place where the
    # numbers settle it outright. The rest are weaker: an entry naming a
    # surround or vinyl transfer is a different transfer from a stereo digital
    # stream, and an entry naming its own format can be compared directly.
    rate, bits = playing.get("rate"), playing.get("bits")
    channels = playing.get("channels")
    source = (album.get("source") or "").strip().lower()
    name = str(album.get("album", ""))
    if rate:
        evidence = True
        wire = format_text(rate, bits)
        cd_audio = rate == 44100 and (bits or 16) <= 16
        if not cd_audio and source == "cd":
            score -= 40
            against.append(
                f"a CD, which holds 44.1 kHz/16 bit, where the stream is "
                f"{wire} — a hi-res issue of the same master would measure "
                "much the same, but this entry is not it")
        elif cd_audio and source in ("cd", "download"):
            score += 6
            for_.append(f"a {source} at {wire}, as the stream is")
        elif not cd_audio and source in ("download", "web", "sacd", "blu-ray"):
            score += 6
            for_.append(f"a {source} issue, as a {wire} stream would be")

        if _SURROUND_EDITION.search(f"{name} {source}") and (channels or 2) <= 2:
            score -= 12
            against.append(f"a surround or disc transfer, against a {wire} "
                           "stereo stream")
        elif _VINYL_EDITION.search(f"{name} {source}"):
            score -= 8
            against.append(f"a vinyl rip, against a {wire} stream")

        stated_rate, stated_bits = stated_format(name)
        if stated_rate and stated_rate != rate:
            score -= 15
            against.append(f"transferred at {format_text(stated_rate, stated_bits)}, "
                           f"where the stream is {wire}")
        elif stated_rate and stated_bits and bits and stated_bits != bits:
            score -= 15
            against.append(f"transferred at {format_text(stated_rate, stated_bits)}, "
                           f"where the stream is {wire}")
        elif stated_rate:
            score += 8
            for_.append(f"transferred at {format_text(stated_rate, stated_bits)}, "
                        "as the stream is")

    # -- which disc of the set ------------------------------------------------
    #
    # A double album is filed here one disc per entry, and they do not measure
    # alike: Delicate Sound of Thunder is DR13 on disc 1 and DR14 on disc 2.
    # The disc is only known when the renderer numbers tracks disc*1000 +
    # track, so an entry naming no disc is not held against.
    disc = playing.get("disc")
    named_disc = _DISC_IN_NAME.search(str(album.get("album", "")))
    if isinstance(disc, int) and disc > 0 and named_disc:
        evidence = True
        if int(named_disc.group(1)) == disc:
            score += 10
            for_.append(f"disc {disc} of the set, as the stream is")
        else:
            score -= 25
            against.append(f"disc {named_disc.group(1)} of the set, "
                           f"where the stream is disc {disc}")

    # -- the imprint and the year --------------------------------------------
    #
    # These name an edition directly, where everything above only describes
    # the audio, so a match counts for a lot. A mismatch counts for little:
    # the database's year is the year of the pressing someone measured, while
    # a streaming service dates a record by whichever issue it licensed, and
    # its label field routinely carries the reissue imprint ("Columbia/
    # Legacy") where the database has the original ("Columbia").
    wire_labels = label_names(playing.get("label", ""))
    version_labels = label_names(album.get("label", ""))
    if wire_labels and version_labels:
        evidence = True
        shared = wire_labels & version_labels
        if shared:
            score += 14
            for_.append(f"same label ({sorted(shared)[0].title()})")
        else:
            score -= 5
            against.append(f"released by {album.get('label')}, "
                           f"not {playing.get('label')}")
    elif version_labels:
        unchecked.append(f"released by {album.get('label')} — the renderer "
                         "publishes no label for the stream to compare it to")
    elif wire_labels:
        unchecked.append(f"the stream is on {playing.get('label')}; this "
                         "entry names no label")

    wire_year = release_year(playing.get("year"))
    version_year = release_year(album.get("year"))
    if wire_year and not version_year:
        unchecked.append(f"the stream is tagged {wire_year}; this entry names "
                         "no year")
    elif version_year and not wire_year:
        unchecked.append(f"issued {version_year} — the renderer publishes no "
                         "year for the stream to compare it to")
    if wire_year and version_year:
        evidence = True
        gap = abs(wire_year - version_year)
        if gap == 0:
            score += 14
            for_.append(f"same year ({version_year})")
        elif gap == 1:
            score += 6
            for_.append(f"issued {version_year}, one year off the {wire_year} "
                        "the stream is tagged with")
        else:
            score -= 6
            against.append(f"issued {version_year}, against the {wire_year} "
                           "the stream is tagged with")

    # -- the name ------------------------------------------------------------
    queue_album = str(playing.get("album", "")).strip().lower()
    version_album = str(album.get("album", "")).strip().lower()
    if queue_album and version_album:
        if queue_album == version_album:
            score += 5
        elif queue_album in version_album or version_album in queue_album:
            score += 2

    score = max(0, min(100, score))
    if not evidence:
        verdict = "unknown"
    elif score >= 55:
        # The right track, at the right position, with the right length and on
        # a medium the stream could have come from scores about 65, and one
        # weak signal pulling the other way should not take that below
        # "likely" -- the reasons are there to be read.
        verdict = "likely"
    elif score >= 30:
        verdict = "possible"
    else:
        verdict = "unlikely"
    return {"score": score, "verdict": verdict, "for": for_, "against": against,
            "unchecked": unchecked, "matched_track": matched_index}
