"""Dynamic Range Database lookups (dr.loudness-war.info) for the renderer card.

The panel knows what is playing but not how hard it was mastered: two
pressings of the same album can differ by ten DR, and the loudest one is
usually the one a streaming service serves.  This module asks the community
database which versions exist and what each one measures, so the answer to
"is there a better master of this?" is one button away from the now-playing
line.

There is no public API — the site is server-rendered HTML — so the pages are
parsed.  Only two of them are: the album list (`/`, `/album/list/...`) and one
album's detail page (`/album/view/<id>`).  Both are machine-generated by the
same template, and the parser reads them structurally (table headers name
their columns, `<th scope=row>` labels name their fields) rather than by
position, so a column added upstream shifts nothing.

Everything here is read-only, cached for `cache_ttl`, and paced by a shared
minimum interval: a listener pressing the button repeatedly must not turn the
panel into a scraper.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from html.parser import HTMLParser
import gzip
import re
import threading
import time
import urllib.error
import urllib.parse
import urllib.request

DEFAULT_BASE_URL = "https://dr.loudness-war.info"

# Rows per page in the site's own listing.  Only used to tell a short last
# page from a full one when deciding whether more results exist.
PAGE_SIZE = 25


@dataclass
class Settings:
    enabled: bool = True
    base_url: str = DEFAULT_BASE_URL
    # The box is on the far side of a domestic link and the panel is polled by
    # a browser: a lookup that cannot answer promptly should fail, not hang a
    # request thread.
    timeout: float = 12.0
    cache_ttl: float = 900.0
    # 3 pages = 75 albums, requested already sorted by DR descending, so a
    # truncated result still holds the best masters the database knows.
    max_pages: int = 3
    # Details are fetched one album at a time, on demand; this caps what the
    # "locate the playing track" sweep may ask for in one go.
    max_detail_lookups: int = 24
    min_request_interval: float = 0.3
    max_response_bytes: int = 4 * 1024 * 1024
    user_agent: str = "open-media-drc panel (dynamic range lookup)"


class DrDbError(RuntimeError):
    """A lookup that could not be answered — network, HTTP or parse."""


# ── HTML ────────────────────────────────────────────────────────────────────

_WS = re.compile(r"\s+")
_ALBUM_ID = re.compile(r"/album/view/(\d+)")
# "DR7   0.00 dB   -8.34 dB   4:12 01-I Ain't" — the per-track line every
# DR-meter build writes into the log people upload with an album.  Tools
# differ below this line (MAAT prints more columns, dr14_tmeter fewer), so
# anything that does not match is simply not a track line.
_LOG_TRACK = re.compile(
    r"^\s*DR(\d+)\s+(-?[\d.]+\s*dB)\s+(-?[\d.]+\s*dB)\s+(\d+:\d{2})\s+(.*?)\s*$")


def _clean(text: str) -> str:
    return _WS.sub(" ", text).strip()


class _TableParser(HTMLParser):
    """Every `<table>` on the page as rows of cells.

    A cell keeps its collapsed text, its raw text (log files are `<pre>` and
    their line breaks carry meaning), the hrefs it links to and the DR badges
    it contains — which is everything either page expresses.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.tables: list[list[list[dict]]] = []
        self._table: list[list[dict]] | None = None
        self._row: list[dict] | None = None
        self._cell: dict | None = None
        self._badge: dict | None = None

    # HTMLParser hooks
    def handle_starttag(self, tag: str, attrs) -> None:
        attr = dict(attrs)
        if tag == "table":
            self._table = []
        elif tag == "tr" and self._table is not None:
            self._row = []
        elif tag in ("td", "th") and self._row is not None:
            self._cell = {"header": tag == "th", "parts": [],
                          "links": [], "badges": []}
        elif self._cell is not None:
            if tag == "a" and attr.get("href"):
                self._cell["links"].append(attr["href"])
            elif tag == "span" and "badge-dr" in (attr.get("class") or ""):
                self._badge = {"class": attr.get("class", ""), "text": ""}
                self._cell["badges"].append(self._badge)
            elif tag == "br":
                self._cell["parts"].append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag == "span" and self._badge is not None:
            self._badge = None
        elif tag in ("td", "th") and self._cell is not None:
            raw = "".join(self._cell["parts"])
            self._cell["raw"] = raw
            self._cell["text"] = _clean(raw)
            if self._row is not None:
                self._row.append(self._cell)
            self._cell = None
        elif tag == "tr" and self._row is not None:
            if self._row:
                self._table.append(self._row)      # type: ignore[union-attr]
            self._row = None
        elif tag == "table" and self._table is not None:
            self.tables.append(self._table)
            self._table = None

    def handle_data(self, data: str) -> None:
        if self._badge is not None:
            self._badge["text"] += data
        elif self._cell is not None:
            self._cell["parts"].append(data)

    @classmethod
    def parse(cls, html: str) -> list[list[list[dict]]]:
        parser = cls()
        parser.feed(html)
        parser.close()
        return parser.tables


def _badge_dr(cell: dict) -> int | None:
    """The DR a cell states.  The badge text is the number the site shows;
    its `badge-dr-NN` class is only a colour bucket (everything at or below 7
    is `badge-dr-07`), so the class is a fallback, never the answer."""
    for badge in cell.get("badges", []):
        text = badge["text"].strip()
        if text.isdigit():
            return int(text)
    text = cell.get("text", "").strip()
    return int(text) if text.isdigit() else None


def _album_id(cell: dict) -> int | None:
    for href in cell.get("links", []):
        match = _ALBUM_ID.search(href)
        if match:
            return int(match.group(1))
    return None


def _column_map(header: list[dict]) -> dict:
    """Column name → index, read from the header row.  The DR columns are
    distinguished by their `min`/`max` captions, which is how the site itself
    labels them."""
    index: dict[str, int] = {}
    for position, cell in enumerate(header):
        name = cell.get("text", "").lower()
        if "artist" in name:
            index.setdefault("artist", position)
        elif "album" in name:
            index.setdefault("album", position)
        elif "year" in name:
            index.setdefault("year", position)
        elif "min" in name and "dr" in name:
            index.setdefault("dr_min", position)
        elif "max" in name and "dr" in name:
            index.setdefault("dr_max", position)
        elif "dr" in name:
            index.setdefault("dr", position)
        elif "codec" in name:
            index.setdefault("codec", position)
        elif "source" in name:
            index.setdefault("source", position)
    return index


# Order of the columns as the site has always served them.  Used only when a
# listing arrives with no header row to read.
_POSITIONAL = {"artist": 0, "album": 1, "year": 2, "dr": 3,
               "dr_min": 4, "dr_max": 5, "codec": 6, "source": 7}


def parse_search(html: str, base_url: str = DEFAULT_BASE_URL) -> list[dict]:
    """The album rows of a listing page, in the order the site served them."""
    rows: list[dict] = []
    for table in _TableParser.parse(html):
        header_index: dict = {}
        for cells in table:
            if all(cell["header"] for cell in cells):
                header_index = _column_map(cells)
                continue
            album_id = next((_album_id(cell) for cell in cells
                             if _album_id(cell) is not None), None)
            if album_id is None:
                continue
            index = header_index or _POSITIONAL

            def value(key: str) -> dict | None:
                position = index.get(key)
                return cells[position] if position is not None and position < len(cells) else None

            def text(key: str) -> str:
                cell = value(key)
                return cell["text"] if cell else ""

            def number(key: str) -> int | None:
                cell = value(key)
                return _badge_dr(cell) if cell else None

            rows.append({
                "id":      album_id,
                "artist":  text("artist"),
                "album":   text("album"),
                "year":    text("year"),
                "dr":      number("dr"),
                "dr_min":  number("dr_min"),
                "dr_max":  number("dr_max"),
                "codec":   text("codec"),
                "source":  text("source"),
                "url":     f"{base_url.rstrip('/')}/album/view/{album_id}",
            })
    return rows


# `<th scope="row">` label → field name on the parsed album.  Labels are
# normalised (lower case, no punctuation) before the lookup.
_ALBUM_FIELDS = {
    "artist": "artist",
    "album": "album",
    "year": "year",
    "album dr": "dr",
    "min track dr": "dr_min",
    "max track dr": "dr_max",
    "track dr": "track_dr",
    "codec": "codec",
    "source": "source",
    "label": "label",
    "catalog number": "catalog_number",
    "bar code": "barcode",
    "country": "country",
    "link": "link",
    "comment": "comment",
    "log file": "log",
}


def parse_log_tracks(log: str) -> list[dict]:
    """The per-track table inside an uploaded DR-meter log.

    Album pages carry no structured track list — only the badge row and the
    log someone pasted — but that log names every track next to its DR, which
    is what makes it possible to tell whether a version in the list is the one
    holding the track now playing."""
    tracks: list[dict] = []
    for line in log.splitlines():
        match = _LOG_TRACK.match(line)
        if not match:
            continue
        dr, peak, rms, duration, title = match.groups()
        tracks.append({"dr": int(dr), "peak": _clean(peak), "rms": _clean(rms),
                       "duration": duration, "title": _clean(title)})
    return tracks


def parse_album(html: str, album_id: int | None = None,
                base_url: str = DEFAULT_BASE_URL) -> dict:
    """One album's detail page: the fields it lists, its per-track DR badges,
    and the log it was uploaded with."""
    album: dict = {"id": album_id, "track_dr": [], "tracks": [], "log": ""}
    if album_id is not None:
        album["url"] = f"{base_url.rstrip('/')}/album/view/{album_id}"
    for table in _TableParser.parse(html):
        for cells in table:
            if len(cells) != 2 or not cells[0]["header"]:
                continue
            label = re.sub(r"[.:]", "", cells[0]["text"]).lower().strip()
            field_name = _ALBUM_FIELDS.get(label)
            if field_name is None:
                continue
            cell = cells[1]
            if field_name == "track_dr":
                album["track_dr"] = [int(badge["text"].strip())
                                     for badge in cell["badges"]
                                     if badge["text"].strip().isdigit()]
            elif field_name in ("dr", "dr_min", "dr_max"):
                album[field_name] = _badge_dr(cell)
            elif field_name == "log":
                album["log"] = cell["raw"].strip("\n")
            elif field_name == "link":
                album["link"] = cell["text"]
                album["link_url"] = cell["links"][0] if cell["links"] else ""
            else:
                album[field_name] = cell["text"]
    album["tracks"] = parse_log_tracks(album["log"])
    return album


# ── client ──────────────────────────────────────────────────────────────────

class DrDb:
    """Cached, paced reader for the database's two public pages."""

    def __init__(self, settings: Settings | None = None,
                 fetch=None) -> None:
        self.settings = settings or Settings()
        self._fetch_override = fetch          # tests inject a page source here
        self._cache: dict[str, tuple[float, str]] = {}
        self._lock = threading.Lock()
        self._last_request = 0.0

    # -- transport --

    def _url(self, path: str) -> str:
        return self.settings.base_url.rstrip("/") + path

    def _fetch(self, path: str) -> str:
        """One page, from cache when it is fresh enough.

        The cache is keyed by path, so a detail page opened from the list and
        the same page reopened a minute later cost one request, and the pacing
        below applies only to requests that actually leave the box."""
        now = time.monotonic()
        with self._lock:
            hit = self._cache.get(path)
            if hit and now - hit[0] < self.settings.cache_ttl:
                return hit[1]

        if self._fetch_override is not None:
            html = self._fetch_override(path)
        else:
            html = self._get(path)

        with self._lock:
            self._cache[path] = (time.monotonic(), html)
        return html

    def _pace(self) -> None:
        with self._lock:
            wait = self.settings.min_request_interval - (
                time.monotonic() - self._last_request)
            self._last_request = time.monotonic() + max(0.0, wait)
        if wait > 0:
            time.sleep(wait)

    def _get(self, path: str) -> str:
        self._pace()
        request = urllib.request.Request(self._url(path), headers={
            "User-Agent": self.settings.user_agent,
            "Accept": "text/html",
            "Accept-Encoding": "gzip",
        })
        try:
            with urllib.request.urlopen(request, timeout=self.settings.timeout) as response:
                raw = response.read(self.settings.max_response_bytes)
                if (response.headers.get("Content-Encoding") or "").lower() == "gzip":
                    raw = gzip.decompress(raw)
        except urllib.error.HTTPError as error:
            raise DrDbError(f"{self.settings.base_url} answered HTTP {error.code}") from error
        except urllib.error.URLError as error:
            raise DrDbError(f"cannot reach {self.settings.base_url}: {error.reason}") from error
        except OSError as error:
            raise DrDbError(f"cannot reach {self.settings.base_url}: {error}") from error
        return raw.decode("utf-8", "replace")

    # -- queries --

    def search(self, artist: str = "", album: str = "",
               pages: int | None = None) -> dict:
        """Every version of `album` the database lists, best master first.

        The listing is requested already sorted by album DR descending, so a
        result cut short by `max_pages` still holds the versions worth
        knowing about.  An empty `album` is deliberately allowed: the Qobuz
        renderer puts no album tag in MusicPD's queue, and the artist's whole
        shelf is then the only honest starting point."""
        artist, album = artist.strip(), album.strip()
        if not artist and not album:
            raise DrDbError("nothing to look up — give an artist or an album")
        query = urllib.parse.urlencode(
            {key: value for key, value in (("artist", artist), ("album", album)) if value})
        limit = max(1, pages or self.settings.max_pages)

        rows: list[dict] = []
        seen: set[int] = set()
        truncated = False
        for page in range(1, limit + 1):
            html = self._fetch(f"/album/list/{page}/dr/desc?{query}")
            found = parse_search(html, self.settings.base_url)
            fresh = [row for row in found if row["id"] not in seen]
            seen.update(row["id"] for row in fresh)
            rows.extend(fresh)
            if len(found) < PAGE_SIZE:
                break
            if page == limit:
                truncated = True

        rows.sort(key=lambda row: (row["dr"] is None, -(row["dr"] or 0),
                                   row["album"].lower()))
        return {"artist": artist, "album": album, "rows": rows,
                "truncated": truncated,
                "search_url": f"{self._url('/')}?{query}"}

    def album(self, album_id: int) -> dict:
        return parse_album(self._fetch(f"/album/view/{int(album_id)}"),
                           int(album_id), self.settings.base_url)
