# cdin-linux — the Linux CD / S-PDIF input bridge.
#
# The FreeBSD counterpart is the cdin/ subproject (omdrc-cdin, a C daemon that
# talks OSS directly).  Linux ships alsaloop(1), which already reconciles two
# free-running clocks, so the Linux side is a supervisor around it rather than a
# daemon of its own — one script plus one --user unit.  Both were previously
# reachable only from a checkout; installing them makes `make install`
# cover them, so the FreeBSD and Linux CD paths install symmetrically.
#
# alsa-utils (for alsaloop) is a runtime dependency, warned about in
# dependencies.cmake rather than required here: the bridge is optional, and a
# box with no capture card should still install cleanly.

if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    return()
endif()

install(PROGRAMS scripts/omdrc-cdin-alsaloop DESTINATION libexec/omdrc/scripts)

# The unit is installed but deliberately NOT enabled by user-install: the CD
# input is an exclusive source on Linux (one seat on hw:Loopback,0,0), and
# drc.sh starts and stops it as the source changes.  `drc.sh cdin` selects it;
# any rate action hands the loopback back to MPD.
file(READ etc/systemd/user/omdrc-cdin.service.in _cdin)
string(REPLACE "@REPO_DIR@/scripts/omdrc-cdin-alsaloop"
               "${CMAKE_INSTALL_PREFIX}/libexec/omdrc/scripts/omdrc-cdin-alsaloop" _cdin "${_cdin}")
string(REPLACE "@AUDIO_HOME@" "${AUDIO_HOME}" _cdin "${_cdin}")
string(REPLACE "# Template — rendered by cmake/cdin-linux.cmake."
               "# Generated by cmake/cdin-linux.cmake and installed to lib/systemd/user."
               _cdin "${_cdin}")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/omdrc-cdin.service" "${_cdin}")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/omdrc-cdin.service" DESTINATION lib/systemd/user)

install(CODE "message(STATUS \"${OMDRC_GREEN}cdin-linux${OMDRC_RESET}: alsaloop bridge + omdrc-cdin user unit installed (started on demand by drc.sh, not enabled)\")")
